### ISSUE TITLE
Use a asset manager

### ISSUE THREAD

**Issue by xtlsoft** [LoliLin/One#1]
Examples: 
https://github.com/kriswallsmith/assetic
https://github.com/Stolz/Assets

And, composer-assets-manager is a good choice for u to download the static things.

And, if u have a future plan for migarating V8.js, in order to use Uglify.js, please tell me.

**Comment by LynMoe** [comment]
换到了 Node，但用的是 Request 下载，不过 [性能](https://blog.lim-light.com/archives/brand-new-avatar-cache.html) 还是ok的
